# Self-hosted Infisical Database Credentials
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-db-credentials
  namespace: infisical
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "infisical-postgresql,infisical-redis"
spec:
  # Infisical connection settings (self-hosted)
  hostAPI: "https://infisical.stg.rzp.one"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-platform-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: infisical-db-credentials
    secretNamespace: infisical
    creationPolicy: "Owner"
  
  # Secret mappings
  secrets:
    - secretPath: "/infisical-db-password"
      secretKey: "db-password"
    - secretPath: "/infisical-redis-password"
      secretKey: "redis-password"
---
# Self-hosted Infisical Application Secrets
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-app-secrets
  namespace: infisical
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "infisical"
spec:
  # Infisical connection settings (self-hosted)
  hostAPI: "https://infisical.stg.rzp.one"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-platform-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: infisical-secrets
    secretNamespace: infisical
    creationPolicy: "Owner"
  
  # Secret mappings
  secrets:
    - secretPath: "/infisical-auth-secret"
      secretKey: "auth-secret"
    - secretPath: "/infisical-encryption-key"
      secretKey: "encryption-key"
    - secretPath: "/infisical-admin-password"
      secretKey: "admin-password"
