# Longhorn admin password from self-hosted Infisical
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: longhorn-admin-password
  namespace: longhorn-system
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "longhorn-ui"
spec:
  # Infisical connection settings (will be switched to self-hosted after migration)
  hostAPI: "https://infisical.stg.rzp.one"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-platform-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: longhorn-admin-password
    secretNamespace: longhorn-system
    creationPolicy: "Owner"
  
  # Secret mappings
  secrets:
    - secretPath: "/longhorn-admin-password"
      secretKey: "password"
