# Migration Job for Infisical Operator (Cloud to Self-hosted)
apiVersion: batch/v1
kind: Job
metadata:
  name: infisical-operator-migration
  namespace: infisical-secrets-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: infisical-migration
    spec:
      restartPolicy: Never
      serviceAccountName: infisical-migration
      containers:
      - name: migration
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          set -e
          echo "Starting Infisical Operator migration from Cloud to Self-hosted..."
          
          # Wait for self-hosted Infisical to be available
          echo "Waiting for self-hosted Infisical API..."
          while ! curl -k -s https://infisical.stg.rzp.one/api/status > /dev/null; do
            echo "Self-hosted Infisical not ready, waiting 30 seconds..."
            sleep 30
          done
          
          echo "Self-hosted Infisical is available"
          
          # Migration would be handled by updating InfisicalSecret resources
          # to point to the new hostAPI endpoint
          
          echo "Migration preparation complete"
          echo "Manual step required: Update InfisicalSecret resources to use self-hosted endpoint"
          echo "kubectl patch infisicalsecret --all-namespaces --type='merge' -p='{\"spec\":{\"hostAPI\":\"https://infisical.stg.rzp.one\"}}'"
          
        env:
        - name: INFISICAL_CLOUD_ENDPOINT
          value: "https://app.infisical.com"
        - name: INFISICAL_SELF_HOSTED_ENDPOINT
          value: "https://infisical.stg.rzp.one"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
# Service Account for Migration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-migration
  namespace: infisical-secrets-system
---
# ClusterRole for Migration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infisical-migration
rules:
- apiGroups: ["secrets.infisical.com"]
  resources: ["infisicalsecrets"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
# ClusterRoleBinding for Migration
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infisical-migration
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infisical-migration
subjects:
- kind: ServiceAccount
  name: infisical-migration
  namespace: infisical-secrets-system