# OpenObserve Database Credentials
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openobserve-db-credentials
  namespace: observability
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "openobserve-postgresql"
spec:
  # Infisical connection settings (self-hosted)
  hostAPI: "https://infisical.stg.rzp.one"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-platform-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: openobserve-db-credentials
    secretNamespace: observability
    creationPolicy: "Owner"
  
  # Secret mappings
  secrets:
    - secretPath: "/openobserve-db-password"
      secretKey: "db-password"
    - secretPath: "/openobserve-postgres-password"
      secretKey: "postgres-password"
---
# OpenObserve Application Secrets
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openobserve-app-secrets
  namespace: observability
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "openobserve"
spec:
  # Infisical connection settings (self-hosted)
  hostAPI: "https://infisical.stg.rzp.one"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-platform-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: openobserve-secrets
    secretNamespace: observability
    creationPolicy: "Owner"
  
  # Secret mappings with static and dynamic values
  secrets:
    - secretPath: "/openobserve-root-password"
      secretKey: "root-user-password"
    - secretPath: "/openobserve-jwt-secret"
      secretKey: "jwt-secret"
    - secretPath: "/openobserve-s3-access-key"
      secretKey: "s3-access-key"
    - secretPath: "/openobserve-s3-secret-key"
      secretKey: "s3-secret-key"
  
  # Static data (non-secret configuration)
  data:
    root-user-email: "admin@rzp.one"
