apiVersion: v1
kind: Secret
metadata:
  name: infisical-auth-credentials
  namespace: external-secrets-system
type: Opaque
stringData:
  client-id: "INFISICAL_CLIENT_ID_PLACEHOLDER"
  client-secret: "INFISICAL_CLIENT_SECRET_PLACEHOLDER"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-platform-secrets
spec:
  provider:
    infisical:
      auth:
        universalAuth:
          secretsScope:
            projectSlug: "platform-secrets"
            environment: "stg"
          credentialsRef:
            clientId:
              name: infisical-auth-credentials
              key: client-id
              namespace: external-secrets-system
            clientSecret:
              name: infisical-auth-credentials
              key: client-secret
              namespace: external-secrets-system
      hostAPI: "https://infisical.stg.rzp.one"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-core-secrets
spec:
  provider:
    infisical:
      auth:
        universalAuth:
          secretsScope:
            projectSlug: "core-secrets"
            environment: "stg"
          credentialsRef:
            clientId:
              name: infisical-auth-credentials
              key: client-id
              namespace: external-secrets-system
            clientSecret:
              name: infisical-auth-credentials
              key: client-secret
              namespace: external-secrets-system
      hostAPI: "https://infisical.stg.rzp.one"
