---
formatter:
  type: basic
  line_ending: lf
  force_array_style: block
  include_document_start: true
  trim_trailing_whitespace: true
  eof_newline: true
  retain_line_breaks_single: true
  indent_root_array: true
