apiVersion: apps/v1
kind: Deployment
metadata:
  name: infisical
  namespace: stg-infisical
  labels:
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: pulumi
    app.kubernetes.io/name: infisical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infisical
  template:
    metadata:
      labels:
        app: infisical
    spec:
      serviceAccountName: infisical
      containers:
      - name: infisical
        image: infisical/infisical:latest-postgres
        ports:
        - containerPort: 8080
        env:
        - name: DB_CONNECTION_URI
          value: postgresql://infisical:JzT6NSL8LjmAPEYHdXtZTJS2rTXKyw1g@infisical-postgresql:5432/infisical
        - name: REDIS_URL
          value: redis://:dTutxzsO0KezkQnwSRE3DiOCTWlFDgFn@infisical-redis-master:6379
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              key: AUTH_SECRET
              name: infisical-app-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              key: ENCRYPTION_KEY
              name: infisical-app-secret
        - name: SITE_URL
          valueFrom:
            secretKeyRef:
              key: SITE_URL
              name: infisical-app-secret
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1