---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-harness
  namespace: harness
  labels:
    app.kubernetes.io/name: svc-harness
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: platform-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harness-role
  namespace: harness
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harness-rolebinding
  namespace: harness
subjects:
  - kind: ServiceAccount
    name: svc-harness
    namespace: harness
roleRef:
  kind: Role
  name: harness-role
  apiGroup: rbac.authorization.k8s.io
