apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: infisical-core-secrets
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-token: "{{ .cloudflareApiToken }}"
  data:
  - secretKey: cloudflareApiToken
    remoteRef:
      key: cloudflare-api-token
