---
apiVersion: v1
kind: Namespace
metadata:
  name: harness
  labels:
    name: harness
    app.kubernetes.io/name: harness
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: platform-services
  annotations:
    argocd.argoproj.io/sync-wave: "0"
