apiVersion: v1
kind: Namespace
metadata:
  name: netdata
  labels:
    name: netdata
    app.kubernetes.io/name: netdata
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: platform-services
  annotations:
    argocd.argoproj.io/sync-wave: "0"