---
apiVersion: v1
kind: Namespace
metadata:
  name: vector-agent
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
    # Required Pod Security Standards for Vector Agent privileged access
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: vector-aggregator
  labels:
    app.kubernetes.io/name: vector-aggregator
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
  annotations:
    argocd.argoproj.io/sync-wave: "0"
