apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
    app.kubernetes.io/name: metallb-system
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: core-platform
    # Required Pod Security Standards for MetalLB privileged access
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    argocd.argoproj.io/sync-wave: "0"