---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: core
  annotations:
    argocd.argoproj.io/sync-wave: "0"
