apiVersion: v1
kind: Service
metadata:
  name: zitadel-metrics
  namespace: zitadel
  labels:
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/component: metrics
spec:
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app.kubernetes.io/name: zitadel
# ServiceMonitor disabled - requires Prometheus Operator CRDs
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: zitadel
#   namespace: zitadel
#   labels:
#     app.kubernetes.io/name: zitadel
#     app.kubernetes.io/component: metrics
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: zitadel
#       app.kubernetes.io/component: metrics
#   endpoints:
#   - port: metrics
#     path: /debug/metrics
#     interval: 30s
#     scrapeTimeout: 10s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-grafana-dashboard
  namespace: zitadel
  labels:
    grafana_dashboard: "1"
data:
  zitadel-dashboard.json: |
    {
      "dashboard": {
        "title": "Zitadel Identity Platform",
        "tags": ["zitadel", "identity", "auth"],
        "panels": [
          {
            "title": "Active Sessions",
            "type": "stat",
            "targets": [
              {
                "expr": "zitadel_active_sessions_total",
                "legendFormat": "Active Sessions"
              }
            ]
          },
          {
            "title": "Authentication Requests",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(zitadel_auth_requests_total[5m])",
                "legendFormat": "Auth Requests/sec"
              }
            ]
          },
          {
            "title": "Database Connections",
            "type": "graph",
            "targets": [
              {
                "expr": "zitadel_database_connections",
                "legendFormat": "DB Connections"
              }
            ]
          }
        ]
      }
    }