global:
  postgresql:
    auth:
      username: "zitadel"
      database: "zitadel"
      existingSecret: "zitadel-db-credentials"
      secretKeys:
        userPasswordKey: "zitadel-db-password"
        adminPasswordKey: "zitadel-postgres-password"
        replicationPasswordKey: "zitadel-postgres-replication-password"

architecture: standalone

primary:
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 5Gi

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  podSecurityContext:
    enabled: true
    fsGroup: 1001

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

metrics:
  enabled: false
