# Common Traefik Middleware for HTTPS handling
# Creates standard HTTPS redirect and security headers across namespaces
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-credentials
  namespace: traefik
type: Opaque
data:
  users: YWRtaW46JGFwcjEkSDZsdkgzVi4kQnBWOVJrZ29ZUm4zR1ZLdHZJazlOMC4=
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-credentials
  namespace: longhorn-system
type: Opaque
data:
  users: YWRtaW46JGFwcjEkSDZsdkgzVi4kQnBWOVJrZ29ZUm4zR1ZLdHZJazlOMC4=
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-credentials
  namespace: observability
type: Opaque
data:
  users: YWRtaW46JGFwcjEkSDZsdkgzVi4kQnBWOVJrZ29ZUm4zR1ZLdHZJazlOMC4=
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: traefik
spec:
  basicAuth:
    secret: basic-auth-credentials
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: basic-auth-credentials
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: observability
spec:
  basicAuth:
    secret: basic-auth-credentials
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: zitadel
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: '11'
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000