# Shared Zitadel Authentication Middleware
# This creates the middleware in multiple namespaces to avoid cross-namespace references
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: zitadel-auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "16" # After Zitadel is deployed
spec:
  forwardAuth:
    address: "http://zitadel-auth-proxy.zitadel.svc.cluster.local:4181/api/verify"
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Name"
      - "Remote-Email"
      - "Remote-Groups"
    trustForwardHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: zitadel-auth
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "16" # After Zitadel is deployed
spec:
  forwardAuth:
    address: "http://zitadel-auth-proxy.zitadel.svc.cluster.local:4181/api/verify"
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Name"
      - "Remote-Email"
      - "Remote-Groups"
    trustForwardHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: zitadel-auth
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "16" # After Zitadel is deployed
spec:
  forwardAuth:
    address: "http://zitadel-auth-proxy.zitadel.svc.cluster.local:4181/api/verify"
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Name"
      - "Remote-Email"
      - "Remote-Groups"
    trustForwardHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: zitadel-auth
  namespace: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "16" # After Zitadel is deployed
spec:
  forwardAuth:
    address: "http://zitadel-auth-proxy.zitadel.svc.cluster.local:4181/api/verify"
    authResponseHeaders:
      - "Remote-User"
      - "Remote-Name"
      - "Remote-Email"
      - "Remote-Groups"
    trustForwardHeader: true
