---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-agent
  namespace: vector-agent
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-agent-role
  labels:
    app.kubernetes.io/name: vector-agent-role
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
rules:
  # Essential for log collection
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
    verbs:
      - "get"
      - "list"
      - "watch"
    # Node-level metrics and info
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "nodes/metrics"
      - "nodes/proxy"
    verbs:
      - "get"
      - "list"
      - "watch"
    # Namespace context for logs
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
    # Service discovery for enrichment
  - apiGroups:
      - ""
    resources:
      - "services"
      - "endpoints"
    verbs:
      - "get"
      - "list"
      - "watch"
    # Workload metadata for log enrichment
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "replicasets"
      - "daemonsets"
      - "statefulsets"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-agent-rolebinding
  labels:
    app.kubernetes.io/name: vector-agent-rolebinding
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-agent-role
subjects:
  - kind: ServiceAccount
    name: vector-agent
    namespace: vector-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-aggregator
  namespace: observability
  labels:
    app.kubernetes.io/name: vector-aggregator
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-aggregator-role
  labels:
    app.kubernetes.io/name: vector-aggregator-role
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
rules:
  # Only needs basic namespace discovery for routing
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-aggregator-rolebinding
  labels:
    app.kubernetes.io/name: vector-aggregator-rolebinding
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-aggregator-role
subjects:
  - kind: ServiceAccount
    name: vector-aggregator
    namespace: observability
