apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-iscsi-installation
  namespace: longhorn-system
  labels:
    app: longhorn-iscsi-installation
spec:
  selector:
    matchLabels:
      app: longhorn-iscsi-installation
  template:
    metadata:
      labels:
        app: longhorn-iscsi-installation
    spec:
      hostNetwork: true
      hostPID: true
      privileged: true
      tolerations:
      - operator: Exists
      containers:
      - name: iscsi-installation
        image: busybox:1.36
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Installing open-iscsi on $(hostname)..."

          # Check if already installed
          if chroot /host which iscsiadm >/dev/null 2>&1; then
            echo "✓ open-iscsi already installed"
            sleep 3600  # Keep pod running
            exit 0
          fi

          # Install based on detected OS
          if chroot /host test -f /etc/debian_version; then
            echo "Detected Debian/Ubuntu - installing open-iscsi"
            chroot /host apt-get update
            chroot /host apt-get install -y open-iscsi
            chroot /host systemctl enable iscsid
            chroot /host systemctl start iscsid
            echo "✓ open-iscsi installed and started"
          elif chroot /host test -f /etc/redhat-release; then
            echo "Detected RHEL/CentOS - installing iscsi-initiator-utils"
            chroot /host yum install -y iscsi-initiator-utils
            chroot /host systemctl enable iscsid
            chroot /host systemctl start iscsid
            echo "✓ iscsi-initiator-utils installed and started"
          else
            echo "⚠ Unsupported OS - manual installation may be required"
            exit 1
          fi

          # Keep the pod running
          sleep 3600
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      restartPolicy: Always
