---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cloudflare-api-token
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: core
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "cert-manager"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets
  managedSecretReference:
    secretName: cloudflare-api-token
    secretNamespace: cert-manager
    creationPolicy: "Owner"
    secretType: Opaque
  resyncInterval: 60
