# Longhorn admin password from Infisical Cloud
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: longhorn-admin-password
  namespace: longhorn-system
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "longhorn-ui"
spec:
  hostAPI: https://app.infisical.com/api

  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets-system

  # Target Kubernetes secret
  managedSecretReference:
    secretName: longhorn-admin-password
    secretNamespace: longhorn-system
    creationPolicy: "Owner"
    secretType: Opaque

  resyncInterval: 60
