apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: netdata-secrets
  namespace: netdata
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "netdata"
spec:
  hostAPI: "https://app.infisical.com/api"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "infisical-secrets-system"

  # Managed secrets
  managedSecretReference:
    secretName: "netdata-secrets"
    secretNamespace: "netdata"
    secretType: "Opaque"