---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: netdata-secrets
  namespace: netdata
  labels:
    app.kubernetes.io/name: netdata-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: core
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "netdata"
spec:
  hostAPI: "https://app.infisical.com/api"
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/netdata"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets
  managedSecretReference:
    secretName: netdata-secrets
    secretNamespace: netdata
    creationPolicy: "Owner"
    secretType: Opaque
  resyncInterval: 60
