---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openobserve-secrets
  namespace: observability
  labels:
    app.kubernetes.io/name: openobserve-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: platform
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "openobserve,vector"
spec:
  hostAPI: "https://app.infisical.com/api"
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/openobserve"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets
  managedSecretReference:
    secretName: openobserve-secrets
    secretNamespace: observability
    creationPolicy: "Owner"
    secretType: Opaque
  resyncInterval: 60
