# OpenObserve Database Credentials
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openobserve-db-credentials
  namespace: observability
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "openobserve-postgresql"
spec:
  hostAPI: "https://app.infisical.com/api"

  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets-system

  # Target Kubernetes secret
  managedSecretReference:
    secretName: openobserve-db-credentials
    secretNamespace: observability
    creationPolicy: "Owner"
    secretType: Opaque

  resyncInterval: 60
---
# OpenObserve Application Secrets
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: openobserve-app-secrets
  namespace: observability
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "openobserve"
spec:
  hostAPI: "https://app.infisical.com/api"

  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets-system

  # Target Kubernetes secret
  managedSecretReference:
    secretName: openobserve-secrets
    secretNamespace: observability
    creationPolicy: "Owner"
    secretType: Opaque

  resyncInterval: 60
