# Zitadel Database Credentials
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zitadel-db-credentials
  namespace: zitadel
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "zitadel-postgresql"
spec:
  # Infisical connection settings (self-hosted)
  hostAPI: "https://app.infisical.com"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-cloud-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: zitadel-db-credentials
    secretNamespace: zitadel
    creationPolicy: "Owner"
  
  # Secret mappings
  secrets:
    - secretPath: "/zitadel-db-password"
      secretKey: "db-password"
    - secretPath: "/zitadel-postgres-password"
      secretKey: "postgres-password"
---
# Zitadel Application Secrets
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zitadel-app-secrets
  namespace: zitadel
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "zitadel"
spec:
  # Infisical connection settings (self-hosted)
  hostAPI: "https://app.infisical.com"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-cloud-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: zitadel-app-secrets
    secretNamespace: zitadel
    creationPolicy: "Owner"
  
  # Secret mappings
  secrets:
    - secretPath: "/zitadel-master-key"
      secretKey: "master-key"
---
# Zitadel Auth Proxy Secrets
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zitadel-auth-proxy-secrets
  namespace: zitadel
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "oauth2-proxy"
spec:
  # Infisical connection settings (self-hosted)
  hostAPI: "https://app.infisical.com"
  projectId: "4668a113-ac3d-4cee-911e-8b3bafec27f0"
  environment: "stg"
  
  # Authentication
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        environment: "stg"
      credentialsRef:
        secretName: infisical-cloud-universal-auth
        secretNamespace: infisical-secrets-system
  
  # Target Kubernetes secret
  managedSecretReference:
    secretName: zitadel-auth-proxy-secrets
    secretNamespace: zitadel
    creationPolicy: "Owner"
  
  # Secret mappings
  secrets:
    - secretPath: "/zitadel-auth-proxy-client-id"
      secretKey: "client-id"
    - secretPath: "/zitadel-auth-proxy-client-secret"
      secretKey: "client-secret"
    - secretPath: "/zitadel-auth-proxy-secret"
      secretKey: "session-secret"
