---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zitadel-db-credentials
  namespace: zitadel
  labels:
    app.kubernetes.io/name: zitadel-db-credentials
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: core
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "zitadel-postgresql"
spec:
  hostAPI: "https://app.infisical.com/api"
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/zitadel"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets
  managedSecretReference:
    secretName: zitadel-db-credentials
    secretNamespace: zitadel
    creationPolicy: "Owner"
    secretType: Opaque
  resyncInterval: 60
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zitadel-app-secrets
  namespace: zitadel
  labels:
    app.kubernetes.io/name: zitadel-app-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: core
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "zitadel"
spec:
  hostAPI: "https://app.infisical.com/api"
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/zitadel"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets
  managedSecretReference:
    secretName: zitadel-app-secrets
    secretNamespace: zitadel
    creationPolicy: "Owner"
    secretType: Opaque
  resyncInterval: 60
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: zitadel-auth-proxy-secrets
  namespace: zitadel
  labels:
    app.kubernetes.io/name: zitadel-auth-proxy-secrets
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: core
  annotations:
    secrets.infisical.com/auto-reload: "true"
    secrets.infisical.com/auto-restart: "oauth2-proxy"
spec:
  hostAPI: "https://app.infisical.com/api"
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "rzp-infra"
        envSlug: "stg"
        secretsPath: "/zitadel"
        recursive: true
      credentialsRef:
        secretName: infisical-auth-credentials
        secretNamespace: infisical-secrets
  managedSecretReference:
    secretName: zitadel-auth-proxy-secrets
    secretNamespace: zitadel
    creationPolicy: "Owner"
    secretType: Opaque
  resyncInterval: 60
