apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-infisical-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # After Infisical operator
  labels:
    app.kubernetes.io/name: core-infisical-secrets
    app.kubernetes.io/component: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/core/infisical-secrets
    directory:
      exclude: "auth-credentials.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
