apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Before External Secrets but after namespaces
  labels:
    app.kubernetes.io/name: infisical-secrets-operator
    app.kubernetes.io/component: infrastructure
spec:
  project: default
  source:
    repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    chart: secrets-operator
    targetRevision: 0.8.2
    helm:
      values: |
        # Install CRDs
        installCRDs: true

        # Controller configuration
        controllerManager:
          replicas: 2

          # Resource configuration
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

          # Security context
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534

          # Pod security context
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 65534

          # Service monitor for metrics
          serviceMonitor:
            enabled: false  # Disabled for homelab

          # Pod disruption budget
          podDisruptionBudget:
            enabled: true
            minAvailable: 1

          # Affinity for high availability
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - infisical-secrets-operator
                  topologyKey: kubernetes.io/hostname

        # Global configuration
        config:
          # TLS configuration for self-hosted instances
          tls:
            skipVerify: false

          # Default sync interval
          syncInterval: "15s"

          # Auto-restart deployments when secrets change
          autoRestart:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: infisical-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-infisical-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # After Infisical operator
  labels:
    app.kubernetes.io/name: core-infisical-secrets
    app.kubernetes.io/component: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/config/infisical
    directory:
      exclude: "auth-credentials.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
