apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"  # After Traefik
  labels:
    app.kubernetes.io/name: longhorn-config
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/core/longhorn-config
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true