---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: core
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.15.2
      helm:
        valueFiles:
          - $values/kubernetes/config/metallb/metallb-values.yaml
    - repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: metallb-webhook-configuration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/deprecated.daemonset.template.generation
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/containers/1/resources
        - /spec/template/spec/containers/2/resources
        - /spec/template/spec/initContainers/0/resources
        - /spec/template/spec/initContainers/1/resources
        - /spec/template/spec/initContainers/2/resources

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: metallb-config
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: core
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/config/metallb
    directory:
      exclude: "metallb-values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
