apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: stg-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.15.2
    helm:
      values: |
        # Controller - single replica with security
        controller:
          enabled: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 65534
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
        # Speaker - with control plane tolerations
        speaker:
          enabled: true
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
              add: ["NET_RAW"]
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
            - key: "node-role.kubernetes.io/master"
              operator: "Exists"
              effect: "NoSchedule"
        # Webhook - minimal resources
        webhook:
          enabled: true
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 65534
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
        # Custom resources for IP pool configuration
        extraResources:
          - apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: stg-ip-pool
              namespace: stg-metallb
            spec:
              addresses:
                - 10.10.0.200-10.10.0.201
          - apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: stg-l2-advertisement
              namespace: stg-metallb
            spec:
              ipAddressPools:
                - stg-ip-pool
  destination:
    server: https://kubernetes.default.svc
    namespace: stg-metallb
  syncPolicy:
    automated:
      prune: false # Temporary - disable prune during adoption
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - Replace=true # Adopt existing resources
    - Prune=false # Temporary - prevent deletion during adoption
