apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # After Longhorn
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 36.3.0
    helm:
      values: |
        # Install CRDs for Middleware, IngressRoute, etc.
        installCRDs: true

        # Deployment - single replica for homelab (matching Pulumi)
        deployment:
          enabled: true
          replicas: 1

        # Service - LoadBalancer for external access with specific IP
        service:
          enabled: true
          type: LoadBalancer
          spec:
            loadBalancerIP: "10.10.0.200"

        # Ports - homelab standard matching staging environment
        ports:
          web:
            port: 8000
            expose:
              default: false  # HTTP disabled for security
            redirections:
              entryPoint:
                to: websecure
                scheme: https
                permanent: true
          websecure:
            port: 443  # Matching staging environment
            expose:
              default: true
            exposedPort: 443
            tls:
              enabled: true

        # Ingress class - default for cluster
        ingressClass:
          enabled: true
          isDefaultClass: true

        # Security and redirect configuration
        globalArguments:
          - "--global.sendanonymoususage=false"
          - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
          - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

        # Production-ready resource limits (matching Pulumi)
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"

        # Dashboard configuration with proper ingress
        ingressRoute:
          dashboard:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
            matchRule: Host(`traefik.stg.rzp.one`)
            entryPoints: ["websecure"]
            tls:
              secretName: traefik-dashboard-tls

        # Disable built-in ACME (cert-manager handles certificates)
        certificatesResolvers: {}

        # Global security settings
        additionalArguments:
          - "--global.checknewversion=false"

        # Persistence for configuration and certificates
        persistence:
          enabled: true
          size: 1Gi
          storageClass: "longhorn"
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ""
    kind: Service
    name: "*"
    jsonPointers:
    - /status/loadBalancer/ingress
