---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harness
  namespace: argocd
  labels:
    app.kubernetes.io/name: harness
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: platform-services
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/config/harness
  destination:
    server: https://kubernetes.default.svc
    namespace: harness
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
