apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: infisical-postgres
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.32
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: "infisical"
              existingSecret: "infisical-db-credentials"
              secretKeys:
                userPasswordKey: "db-password"
              database: "infisical"

        architecture: standalone

        primary:
          persistence:
            enabled: true
            storageClass: "longhorn"
            size: 2Gi

          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          podSecurityContext:
            enabled: true
            fsGroup: 1001

          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsNonRoot: true

        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app.kubernetes.io/name: infisical-redis
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.6.4
    helm:
      values: |
        auth:
          enabled: true
          existingSecret: "infisical-db-credentials"
          existingSecretPasswordKey: "redis-password"

        architecture: standalone

        master:
          persistence:
            enabled: true
            storageClass: "longhorn"
            size: 512Mi

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

          podSecurityContext:
            enabled: true
            fsGroup: 1001

          containerSecurityContext:
            enabled: true
            runAsUser: 1001
            runAsNonRoot: true

        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: infisical-app
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/core/infisical-config
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
