apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15" # After core platform services
  labels:
    app.kubernetes.io/name: netdata
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://netdata.github.io/helmchart
    chart: netdata
    targetRevision: 3.7.141
    helm:
      values: |
        # Netdata configuration for homelab monitoring
        image:
          repository: netdata/netdata
          tag: v2.6.0
          pullPolicy: Always

        # Replica configuration - single instance for homelab
        replicaCount: 1

        # Service configuration
        service:
          type: ClusterIP
          port: 19999
          targetPort: 19999
          annotations: {}

        # Ingress configuration
        ingress:
          enabled: true
          className: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-staging"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: "netdata-default-headers@kubernetescrd"
          hosts:
            - host: netdata.stg.rzp.one
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: netdata-tls
              hosts:
                - netdata.stg.rzp.one

        # Resource configuration
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Security context
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
              - SYS_ADMIN
            drop:
              - ALL
          readOnlyRootFilesystem: false

        podSecurityContext:
          runAsUser: 201
          runAsGroup: 201
          runAsNonRoot: true

        # Parent configuration for Netdata Cloud integration
        parent:
          enabled: true
          env:
            - name: NETDATA_CLAIM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: netdata-secrets
                  key: netdata-claim-token
            - name: NETDATA_CLAIM_ROOMS
              valueFrom:
                secretKeyRef:
                  name: netdata-secrets
                  key: netdata-claim-room
            - name: NETDATA_CLAIM_URL
              value: "https://app.netdata.cloud"
            - name: DO_NOT_TRACK
              value: "1"
          
        # Persistence for metrics storage
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: "2Gi"
          accessModes:
            - ReadWriteOnce

        # Host monitoring capabilities
        hostNetwork: false

        # RBAC permissions for Kubernetes monitoring
        rbac:
          create: true

        serviceAccount:
          create: true
          annotations: {}

        # Node selector and tolerations
        nodeSelector: {}
        tolerations: 
          - operator: Exists
        
        affinity: {}

        # Netdata configuration
        configmap:
          enabled: true
          data:
            netdata.conf: |
              [global]
                  hostname = netdata-k3s
                  history = 3600
                  error log = stderr
                  access log = none
                  debug log = none

              [web]
                  mode = static-threaded
                  listen backlog = 4096
                  default port = 19999
                  bind to = 0.0.0.0:19999
                  disconnect idle clients after seconds = 60
                  timeout for first request = 60
                  accept a streaming request every seconds = 0
                  respect do not track policy = no
                  x-frame-options response header =
                  allow connections from = localhost *
                  allow dashboard from = localhost *
                  allow badges from = *
                  allow streaming from = *
                  allow netdata.conf from = localhost fd* 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
                  allow management from = localhost
                  enable gzip compression = yes
                  gzip compression strategy = default
                  gzip compression level = 6

              [plugins]
                  cgroups = yes
                  proc = yes
                  diskspace = yes
                  tc = no
                  idlejitter = yes
                  enable running new plugins = yes
                  check for new plugins every = 60
                  python.d = yes
                  charts.d = yes
                  go.d = yes
                  node.d = yes
                  apps = yes
                  statsd = yes

        # Child configuration for distributed monitoring
        child:
          enabled: false

        # Parent configuration
        parent:
          enabled: false

        # k8s-state-metrics integration
        k8sState:
          enabled: true

        # Enable various collectors
        collectors:
          kubelet:
            enabled: true
          kubeProxy:
            enabled: true
          systemd:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: "*"
    jsonPointers:
    - /data