---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: argocd
  labels:
    app.kubernetes.io/name: netdata
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    - repoURL: https://netdata.github.io/helmchart
      chart: netdata
      targetRevision: 3.7.141
      helm:
        valueFiles:
          - $values/kubernetes/config/netdata/netdata-values.yaml
    - repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: "*"
      jsonPointers:
        - /data
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: netdata-config
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/config/netdata
    directory:
      exclude: "netdata-values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
