---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10" # After core CRDs are installed and ready
  labels:
    app.kubernetes.io/name: platform-services
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/platform
    directory:
      recurse: true
      include: "{*.yaml,namespaces/*.yaml}"
      exclude: "platform-services.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    # External Secrets Operator drift
    - group: external-secrets.io
      kind: SecretStore
      name: "*"
      jsonPointers:
        - /status
    - group: external-secrets.io
      kind: ExternalSecret
      name: "*"
      jsonPointers:
        - /status
        # Standard K8s-managed secret and configmap data
    - group: ""
      kind: Secret
      name: "*"
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      name: "*"
      jsonPointers:
        - /data
        # StatefulSet and Deployment annotations
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/deployment.kubernetes.io~1revision
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/deployment.kubernetes.io~1revision
        # Ingress annotations that may be added by controllers
    - group: networking.k8s.io
      kind: Ingress
      name: "*"
      jsonPointers:
        - /metadata/annotations/ingress.kubernetes.io~1ssl-redirect
