apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"  # After namespaces (wave 0), before services need middleware
  labels:
    app.kubernetes.io/name: shared-config
    app.kubernetes.io/component: shared
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/shared-config
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: argoproj.io
    kind: Application
    name: shared-config
    jsonPointers:
    - /spec/source/directory/recurse
  - group: traefik.io
    kind: Middleware
    jsonPointers:
    - /metadata/annotations
    - /status