---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-agent
  namespace: argocd
  labels:
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: platform-services
  annotations:
    argocd.argoproj.io/sync-wave: "11"  # Deploy before aggregator
spec:
  project: default
  sources:
    - repoURL: https://helm.vector.dev
      chart: vector
      targetRevision: 0.34.0
      helm:
        valueFiles:
          - $values/kubernetes/config/vector/vector-agent-values.yaml
    - repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vector-agent  # Separate namespace for agents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /metadata/annotations/deprecated.daemonset.template.generation
    - group: ""
      kind: Secret
      name: "*"
      jsonPointers:
        - /data
