---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
  labels:
    app.kubernetes.io/name: zitadel-postgres
    app.kubernetes.io/component: platform
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 15.5.32
      helm:
        valueFiles:
          - $values/kubernetes/config/zitadel/zitadel-postgres-values.yaml
    - repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /metadata/annotations/deployment.kubernetes.io~1revision
    - group: ""
      kind: Secret
      name: "*"
      jsonPointers:
        - /data

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  labels:
    app.kubernetes.io/name: zitadel-app
    app.kubernetes.io/component: platform
spec:
  project: default
  sources:
    - repoURL: https://charts.zitadel.com
      chart: zitadel
      targetRevision: 8.13.4
      helm:
        valueFiles:
          - $values/kubernetes/config/zitadel/zitadel-app-values.yaml
    - repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /metadata/annotations/deployment.kubernetes.io~1revision
    - group: networking.k8s.io
      kind: Ingress
      name: "*"
      jsonPointers:
        - /metadata/annotations/ingress.kubernetes.io~1ssl-redirect
    - group: ""
      kind: Secret
      name: "*"
      jsonPointers:
        - /data

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  labels:
    app.kubernetes.io/name: zitadel-config
    app.kubernetes.io/component: platform
spec:
  project: default
  source:
    repoURL: https://github.com/rzp-labs/rzp-infrastructure.git
    targetRevision: HEAD
    path: kubernetes/config/zitadel
    directory:
      exclude: "*-values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
