# Basic authentication for staging environment dashboards
# Username: admin, Password: staging123
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-credentials
  namespace: traefik
type: Opaque
data:
  users: YWRtaW46JGFwcjEkSDZsdkgzVi4kQnBWOVJrZ29ZUm4zR1ZLdHZJazlOMC4=  # admin:staging123
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-credentials
  namespace: longhorn-system
type: Opaque
data:
  users: YWRtaW46JGFwcjEkSDZsdkgzVi4kQnBWOVJrZ29ZUm4zR1ZLdHZJazlOMC4=  # admin:staging123
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-credentials
  namespace: observability
type: Opaque
data:
  users: YWRtaW46JGFwcjEkSDZsdkgzVi4kQnBWOVJrZ29ZUm4zR1ZLdHZJazlOMC4=  # admin:staging123
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: traefik
spec:
  basicAuth:
    secret: basic-auth-credentials
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: basic-auth-credentials
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: observability
spec:
  basicAuth:
    secret: basic-auth-credentials